# Generated by Django 6.1.1 on 2026-09-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
                ('profile_image_url', models.URLField()),
                ('bio_text', models.TextField()),
                ('join_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
